digest: f5c0421a
name: dataset
profile: '{"num_rows": 200, "num_elements": 1000}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "feature_0", "required": true},
  {"type": "double", "name": "feature_1", "required": true}, {"type": "double", "name":
  "feature_2", "required": true}, {"type": "double", "name": "feature_3", "required":
  true}, {"type": "double", "name": "feature_4", "required": true}]}'
source: '{"tags": {"mlflow.user": "User", "mlflow.source.name": "src/train_model.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "2373c047ef3f76905fabb976eb8f48db32967cee"}}'
source_type: code
